name: Build Jenkins master image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_upload:
    name: Build and upload image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: make build VERSION=2

      - name: Push to docker hub
        run: |
          TAG=$(grep "io.jenkins.version=" 2/Dockerfile.localdev | grep -o "[0-9]\.[0-9]*\.[0-9]")
          echo $TAG
          sudo docker tag openshift/jenkins-2-centos7:latest henrywangxf/jenkins-2-centos7:$TAG
          sudo docker login -u henrywangxf -p $DOCKER_HUB_TOKEN
          sudo docker push henrywangxf/jenkins-2-centos7
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.HENRYWANGXF_DOCKER_HUB_TOKEN }}
